ini_open(game_save_id + writefile + ".mif");
ini_write_string("mif", "main", "!MIF![1600](800)");
savestring = "";
line = 0;
writefile = writefile;
rep = 1200;
r = 0;
g = 0;
b = 0;
c = c_black;
_x = 1600;
_y = 800;