ini_open(program_directory + writefile + ".mif");
ini_write_string("mif", "main", "!MIF![1600](800)");
savestring = "";
writefile = writefile;
line = 0;
r = 0;
g = 0;
b = 0;
c = c_black;
_x = 1600;
_y = 800;